feat(dataTable): saving method optimization for colDefs
i-Cell-Mobilsoft-Open-Source/icell-data-table pull request #230
Opened 2022-03-28 14:11 UTC by egrycs

2022-03-28 14:22 UTC, sanyisuveges approved these changes

2022-03-29 05:38 UTC, welsen requested changes
Please add the new property `actionColumn` to the column settings section of the `README.adoc`

2022-03-29 05:38 UTC, welsen commented on package.json
> +  "version": "3.0.6",
this should be the same as the current version published (3.0.5)

2022-03-29 05:38 UTC, welsen commented on src/data-table.component.ts
> +          ? (this.columnSettings as DataTableColumnDefinition[]).filter((i) => !i.hideable && i.visible)
👍

2022-03-29 07:43 UTC, welsen approved these changes
🦅

2022-03-29 07:45 UTC, merged